name: flutter_monitor_native
description: Optional Flutter Monitor native bridge package for future platform signals.
version: 0.1.0
homepage: https://github.com/xinqingaa/flutter_monitor
repository: https://github.com/xinqingaa/flutter_monitor
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_monitor_core: ^0.1.0
  flutter_monitor_sdk: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttermonitor.nativebridge
        pluginClass: FlutterMonitorNativePlugin
      ios:
        pluginClass: FlutterMonitorNativePlugin
