import '../constants/field_paths.dart';
import '../privacy/privacy_level.dart';
import 'field_definition.dart';
import 'field_requirement.dart';
import 'field_value_type.dart';

class FieldRegistry {
  FieldRegistry(Iterable<FieldDefinition> fields)
    : _fields = {for (final field in fields) field.path: field};

  factory FieldRegistry.defaults() => FieldRegistry(defaultFieldDefinitions);

  final Map<String, FieldDefinition> _fields;

  FieldDefinition? lookup(String path) => _fields[path];

  bool contains(String path) => _fields.containsKey(path);

  Iterable<FieldDefinition> get fields => _fields.values;
}

const defaultFieldDefinitions = <FieldDefinition>[
  FieldDefinition(
    path: FieldPaths.schemaVersion,
    valueType: FieldValueType.string,
    requirement: FieldRequirement.required,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.eventId,
    valueType: FieldValueType.string,
    requirement: FieldRequirement.required,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.timestamp,
    valueType: FieldValueType.timestamp,
    requirement: FieldRequirement.required,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.startTime,
    valueType: FieldValueType.timestamp,
    requirement: FieldRequirement.conditional,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.endTime,
    valueType: FieldValueType.timestamp,
    requirement: FieldRequirement.conditional,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.durationMs,
    valueType: FieldValueType.durationMs,
    requirement: FieldRequirement.conditional,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.signalType,
    valueType: FieldValueType.string,
    requirement: FieldRequirement.required,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.name,
    valueType: FieldValueType.string,
    requirement: FieldRequirement.required,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.level,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.status,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.priority,
    valueType: FieldValueType.string,
    requirement: FieldRequirement.defaulted,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.sessionId,
    valueType: FieldValueType.string,
    requirement: FieldRequirement.conditional,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.traceId,
    valueType: FieldValueType.string,
    requirement: FieldRequirement.conditional,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.spanId,
    valueType: FieldValueType.string,
    requirement: FieldRequirement.conditional,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.parentSpanId,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resource,
    valueType: FieldValueType.object,
    requirement: FieldRequirement.required,
    privacyLevel: PrivacyLevel.mixed,
  ),
  FieldDefinition(
    path: FieldPaths.context,
    valueType: FieldValueType.object,
    requirement: FieldRequirement.required,
    privacyLevel: PrivacyLevel.mixed,
  ),
  FieldDefinition(
    path: FieldPaths.attributes,
    valueType: FieldValueType.object,
    privacyLevel: PrivacyLevel.mixed,
  ),
  FieldDefinition(
    path: FieldPaths.payload,
    valueType: FieldValueType.object,
    privacyLevel: PrivacyLevel.mixed,
  ),
  FieldDefinition(
    path: FieldPaths.eventPhase,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceSdkName,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceSdkVersion,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceSdkCoreVersion,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceSdkNativeVersion,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceAppAppKey,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceAppAppName,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.resourceAppAppVersion,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceAppBuildNumber,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceAppPackageName,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceAppEnvironment,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceAppChannel,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceAppFlavor,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceDevicePlatform,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceDeviceModel,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceDeviceManufacturer,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceDeviceOsVersion,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceDeviceIsPhysicalDevice,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceDeviceRefreshRate,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceDeviceDeviceTier,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceRuntimeFlutterVersion,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceRuntimeDartVersion,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.resourceRuntimeIsDebug,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextUserUserId,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.sensitive,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextUserUserType,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextUserUserTags,
    valueType: FieldValueType.array,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextUserCohort,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextRouteName,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextRouteFullName,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextRouteStack,
    valueType: FieldValueType.array,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextRouteSource,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextModuleName,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextModuleScene,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextNetworkType,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextNetworkIsWeakNetwork,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextReleaseReleaseId,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextReleaseFeatureFlags,
    valueType: FieldValueType.array,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextReleaseExperiments,
    valueType: FieldValueType.object,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextLifecycleState,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextLifecyclePreviousState,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextLifecycleIsForeground,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextNativeAvailable,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextNativePlatform,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextNativeProcessId,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.contextNativeBridgeVersion,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextNativeSignalSource,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextMissing,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.contextMissingReason,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.appStartType,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.appStartEndReason,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.appFirstFrameMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.appInteractiveMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.sdkInitDurationMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.nativeStartElapsedMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.pageFirstFrameMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.pageInteractiveMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.pageFrom,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.pageFromFullName,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.pageTo,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.pageToFullName,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.pageInstanceId,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.pageActivePhase,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.pageLoadMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.httpMethod,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.httpUrlNormalized,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.httpStatusCode,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.httpSuccess,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.httpErrorType,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.httpRetryCount,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.httpCacheStatus,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.requestSizeBytes,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.responseSizeBytes,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.uiTarget,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.uiAction,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.businessAction,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.businessResult,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.interactionMode,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.interactionEndReason,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.interactionActiveMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.interactionSettleMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.interactionObserveMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.interactionTimeoutMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.jankCount,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameMaxMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameAvgMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameBudgetMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameFps,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameStability,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameP50Ms,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameP90Ms,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameP99Ms,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameSampleCount,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameSlowCount,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameDroppedCount,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.frameRefreshRate,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memoryRssMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memoryStartRssMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memoryEndRssMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memoryDeltaRssMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memoryEnterRssMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memoryExitRssMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memoryHeapUsedMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.memoryHeapCapacityMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.memoryExternalMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.memoryNativeUsedMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memoryGrowthMb,
    valueType: FieldValueType.number,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memoryGrowthDurationMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memoryPressureLevel,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memorySampleSource,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.memorySamplePhase,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.appExitFlushSuccess,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.nativeSignal,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.nativeThread,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
  ),
  FieldDefinition(
    path: FieldPaths.nativeThreadId,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
  ),
  FieldDefinition(
    path: FieldPaths.nativeCrashType,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.nativeAnrDurationMs,
    valueType: FieldValueType.durationMs,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.nativeOomReason,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
  ),
  FieldDefinition(
    path: FieldPaths.errorType,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.errorMechanism,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.errorHandled,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.errorFatal,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
    indexed: true,
  ),
  FieldDefinition(
    path: FieldPaths.errorThread,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
  ),
  FieldDefinition(
    path: FieldPaths.payloadErrorMessage,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.sensitive,
  ),
  FieldDefinition(
    path: FieldPaths.payloadErrorStacktrace,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.sensitive,
  ),
  FieldDefinition(
    path: FieldPaths.payloadErrorLibrary,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.queryable,
  ),
  FieldDefinition(
    path: FieldPaths.payloadBreadcrumbs,
    valueType: FieldValueType.array,
    privacyLevel: PrivacyLevel.mixed,
  ),
  FieldDefinition(
    path: FieldPaths.payloadTruncated,
    valueType: FieldValueType.boolean,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.payloadTruncatedReason,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.safe,
  ),
  FieldDefinition(
    path: FieldPaths.payloadTrace,
    valueType: FieldValueType.object,
    privacyLevel: PrivacyLevel.mixed,
  ),
  FieldDefinition(
    path: FieldPaths.payloadNative,
    valueType: FieldValueType.object,
    privacyLevel: PrivacyLevel.mixed,
  ),
  FieldDefinition(
    path: FieldPaths.payloadProperties,
    valueType: FieldValueType.object,
    privacyLevel: PrivacyLevel.mixed,
  ),
  FieldDefinition(
    path: FieldPaths.httpUrlQuery,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.forbidden,
    description: 'Raw URL query is forbidden by default.',
  ),
  FieldDefinition(
    path: FieldPaths.httpRequestBody,
    valueType: FieldValueType.object,
    privacyLevel: PrivacyLevel.forbidden,
    description: 'Request body is forbidden by default.',
  ),
  FieldDefinition(
    path: FieldPaths.httpResponseBody,
    valueType: FieldValueType.object,
    privacyLevel: PrivacyLevel.forbidden,
    description: 'Response body is forbidden by default.',
  ),
  FieldDefinition(
    path: FieldPaths.httpRequestHeadersCookie,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.forbidden,
    description: 'Cookies are forbidden by default.',
  ),
  FieldDefinition(
    path: FieldPaths.authToken,
    valueType: FieldValueType.string,
    privacyLevel: PrivacyLevel.forbidden,
    description: 'Tokens are forbidden by default.',
  ),
];
