/** Catalog 统一文案。面向用户的 label 一律中文。 */
export const CatalogLabels = {
  time: '时间',
  route: '路由',
  user: '用户',
  version: '版本',
  environment: '环境',
  platform: '平台',
  session: 'Session',
  eventId: '事件 ID',
  trace: 'Trace',
  requestId: '请求 ID',
  method: '方法',
  url: 'URL',
  statusCode: '状态码',
  businessCode: '业务码',
  duration: '耗时',
  action: '动作',
  result: '结果',
  kind: '类型',
  message: '消息',
  occurrenceCount: '次数',
  handledState: '处理状态',
  status: '状态',
  problems: '问题',
  events: '事件',
} as const;
