import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearch } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, ExternalLink, GitBranch, MousePointerClick } from 'lucide-react';
import type { DomainSearch } from '../../app/router';
import { ScopeFilterBar } from '../../features/scope/scope-filter-bar';
import { SplitPane } from '../../components/layout/split-pane';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { FilterSelect } from '../../components/common/filter-select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/table';
import { Badge } from '../../components/common/status-badge';
import { CopyableId } from '../../components/common/copyable-id';
import { RecordShell } from '../../features/inspector/record-shell';
import { JsonViewer } from '../../features/inspector/json-viewer';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../components/ui/tabs';
import { datasource, queryKeys, useDimensionsQuery, useEventQuery, useSessionQuery } from '../../shared/datasource/queries';
import type { BusinessCatalogItem, BusinessCatalogQuery, ErrorCatalogItem, ErrorCatalogQuery, MonitorEvent, SessionFilters } from '../../shared/datasource/types';
import { formatDateTime, formatTime } from '../../shared/formatting/format';
import { readPath } from '../../shared/event-model/accessors';
import { cn } from '../../shared/formatting/cn';
import { useDebouncedValue } from '../../shared/hooks/use-debounced-value';

type Mode = 'business' | 'errors';
type Item = BusinessCatalogItem | ErrorCatalogItem;

export function BusinessCatalogRoute() { return <DomainCatalog mode="business" />; }
export function ErrorCatalogRoute() { return <DomainCatalog mode="errors" />; }

function DomainCatalog({ mode }: { mode: Mode }) {
  const path = mode === 'business' ? '/business' : '/errors';
  const search = useSearch({ from: path });
  const navigate = useNavigate({ from: path });
  const page = search.page ?? 1;
  const pageSize = search.pageSize ?? 50;
  const query = useMemo(() => mode === 'business' ? businessQuery(search, page, pageSize) : errorQuery(search, page, pageSize), [mode, search, page, pageSize]);
  const catalog = useQuery<{ items: Item[]; total: number; limit: number; offset: number }>({
    queryKey: mode === 'business' ? queryKeys.businessCatalog(query as BusinessCatalogQuery) : queryKeys.errorCatalog(query as ErrorCatalogQuery),
    queryFn: async () => mode === 'business'
      ? datasource.businessCatalog(query as BusinessCatalogQuery)
      : datasource.errorCatalog(query as ErrorCatalogQuery),
  });
  const dimensions = useDimensionsQuery(scopeQuery(search));
  const detail = useEventQuery(search.detail);
  const items = catalog.data?.items ?? [];
  const selected = items.find((item) => item.eventId === search.eventId);
  const detailItem = items.find((item) => item.eventId === search.detail) ?? selected;
  const total = catalog.data?.total ?? 0;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const hasDomainFilters = mode === 'business' ? Boolean(search.action || search.result) : Boolean(search.errorType || search.mechanism || search.fatal !== undefined || search.handled !== undefined || search.businessOnly);

  function patch(value: Partial<DomainSearch>, reset = false) { void navigate({ search: (current) => clean({ ...current, ...value, ...(reset ? { page: undefined, eventId: undefined, detail: undefined } : {}) }), replace: reset }); }
  function select(item: Item) { patch({ eventId: item.eventId, detail: window.matchMedia('(max-width: 1023px)').matches ? item.eventId : undefined }); }
  function open(item: Item) { patch({ eventId: item.eventId, detail: item.eventId }); }
  useEffect(() => { if (catalog.data && search.eventId && !items.some((item) => item.eventId === search.eventId)) patch({ eventId: undefined, detail: undefined }); }, [catalog.data, items, search.eventId]);

  const state = catalog.isLoading && !catalog.data ? 'loading' : catalog.isError ? 'error' : items.length === 0 ? ((hasDomainFilters || hasScope(search)) ? 'noResults' : 'empty') : 'ready';
  return <div className="flex h-full min-h-0 flex-col bg-canvas">
    <ScopeFilterBar search={search} dimensions={dimensions.data} onPatch={patch} />
    <DomainFilters mode={mode} search={search} total={total} onPatch={patch} onReset={() => patch(mode === 'business' ? { action: undefined, result: undefined } : { errorType: undefined, mechanism: undefined, fatal: undefined, handled: undefined, businessOnly: undefined }, true)} />
    <SplitPane primary={<div className="grid h-full min-h-0 grid-rows-[minmax(0,1fr)_44px]"><DomainTable mode={mode} items={items} state={state} selectedId={search.eventId} onSelect={select} onOpen={open} onRetry={() => void catalog.refetch()} /><Pager page={page} pageSize={pageSize} totalPages={totalPages} onPatch={patch} /></div>} secondary={<DomainPreview mode={mode} item={selected} onOpen={() => selected && open(selected)} />} />
    <DomainRecord mode={mode} open={Boolean(search.detail)} item={detailItem} event={detail.data} loading={detail.isLoading} error={detail.isError} onClose={() => patch({ detail: undefined })} />
  </div>;
}

function DomainFilters({ mode, search, total, onPatch, onReset }: { mode: Mode; search: DomainSearch; total: number; onPatch: (value: Partial<DomainSearch>, reset?: boolean) => void; onReset: () => void }) {
  return <section className="flex min-w-0 flex-wrap items-center gap-2 border-b border-border-default bg-surface px-3 py-2">{mode === 'business' ? <><CommitInput label="Action" value={search.action} onCommit={(action) => onPatch({ action }, true)} /><FilterSelect value={search.result} placeholder="全部结果" options={['success', 'failed', 'cancelled'].map((value) => ({ value, label: value }))} onChange={(result) => onPatch({ result }, true)} className="w-32" /></> : <><CommitInput label="错误类型" value={search.errorType} onCommit={(errorType) => onPatch({ errorType }, true)} /><FilterSelect value={search.mechanism} placeholder="全部机制" options={['flutter', 'dart', 'native', 'manual', 'custom'].map((value) => ({ value, label: value }))} onChange={(mechanism) => onPatch({ mechanism }, true)} className="w-32" /><TriSelect label="Fatal" value={search.fatal} onChange={(fatal) => onPatch({ fatal }, true)} /><TriSelect label="Handled" value={search.handled} onChange={(handled) => onPatch({ handled }, true)} /><label className="inline-flex h-8 items-center gap-2 rounded-control border border-border-default px-2 text-xs"><input type="checkbox" checked={search.businessOnly === true} onChange={(event) => onPatch({ businessOnly: event.target.checked || undefined }, true)} />仅业务失败</label></>}<span className="text-xs tabular-nums text-text-secondary">{total} 条</span><Button size="sm" variant="ghost" onClick={onReset}>重置领域筛选</Button></section>;
}

function DomainTable({ mode, items, state, selectedId, onSelect, onOpen, onRetry }: { mode: Mode; items: Item[]; state: string; selectedId?: string; onSelect: (item: Item) => void; onOpen: (item: Item) => void; onRetry: () => void }) {
  if (state !== 'ready') return <EmptyState mode={mode} state={state} onRetry={onRetry} />;
  return <div className="h-full overflow-auto bg-surface"><Table className="min-w-[760px] table-fixed text-left text-xs"><TableHeader className="sticky top-0 z-10 bg-subtle text-text-secondary"><TableRow className="h-9 border-border-default hover:bg-subtle">{mode === 'business' ? <><Th className="w-40">时间</Th><Th>Action</Th><Th className="w-24">Result</Th><Th className="w-36">路由</Th><Th className="w-32">用户</Th><Th className="w-28">版本</Th></> : <><Th className="w-40">时间</Th><Th className="w-28">类型</Th><Th>Message</Th><Th className="w-24">Fatal</Th><Th className="w-32">路由</Th><Th className="w-28">版本</Th></>}<Th className="w-14" /></TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.eventId} tabIndex={0} aria-selected={item.eventId === selectedId} className={cn('h-9 border-border-muted outline-none hover:bg-subtle focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-interactive-focusRing', item.eventId === selectedId && 'bg-selected')} onClick={() => onSelect(item)} onDoubleClick={() => onOpen(item)} onKeyDown={(event) => event.key === 'Enter' && onOpen(item)}>{mode === 'business' ? <BusinessCells item={item as BusinessCatalogItem} /> : <ErrorCells item={item as ErrorCatalogItem} />}<Td><Button size="icon" variant="ghost" className="size-7" aria-label={`打开${mode === 'business' ? '埋点' : '异常'}详情`} onClick={(event) => { event.stopPropagation(); onOpen(item); }}><ExternalLink /></Button></Td></TableRow>)}</TableBody></Table></div>;
}
function BusinessCells({ item }: { item: BusinessCatalogItem }) { return <><Td className="font-mono text-[11px]">{formatTime(item.timestamp)}</Td><Td><span className="block truncate font-mono" title={item.action}>{item.action}</span>{item.summary ? <Badge tone="neutral">summary</Badge> : null}</Td><Td className={item.result === 'failed' ? 'font-semibold text-status-danger' : ''}>{item.result ?? '-'}</Td><Td>{item.route ?? '-'}</Td><Td>{item.userId ?? '-'}</Td><Td>{item.appVersion ?? '-'}</Td></>; }
function ErrorCells({ item }: { item: ErrorCatalogItem }) { return <><Td className="font-mono text-[11px]">{formatTime(item.timestamp)}</Td><Td><Badge tone={item.kind === 'business_failure' ? 'warn' : 'danger'}>{item.kind === 'business_failure' ? '业务失败' : 'Error'}</Badge></Td><Td><span className="block truncate" title={item.message ?? item.type}>{item.message ?? item.type}</span></Td><Td>{item.fatal === undefined ? '-' : item.fatal ? 'Fatal' : item.handled ? 'Handled' : '未处理'}</Td><Td>{item.route ?? '-'}</Td><Td>{item.appVersion ?? '-'}</Td></>; }

function DomainPreview({ mode, item, onOpen }: { mode: Mode; item?: Item; onOpen: () => void }) { if (!item) return <div className="grid h-full place-items-center text-sm text-text-muted">选择一行查看摘要</div>; const business = mode === 'business' ? item as BusinessCatalogItem : undefined; const error = mode === 'errors' ? item as ErrorCatalogItem : undefined; return <div className="grid gap-4 p-3 pt-12 text-xs"><div>{business ? <><Badge tone={business.result === 'failed' ? 'danger' : 'good'}>{business.result ?? '未知结果'}</Badge><h2 className="mt-2 break-all font-mono text-sm font-semibold">{business.action}</h2></> : <><Badge tone={error?.kind === 'business_failure' ? 'warn' : 'danger'}>{error?.kind === 'business_failure' ? '业务失败' : 'Error'}</Badge><h2 className="mt-2 break-all text-sm font-semibold">{error?.type}</h2><p className="mt-1 break-words text-text-secondary">{error?.message}</p></>}</div><dl className="grid grid-cols-[72px_1fr] gap-2"><dt>路由</dt><dd className="text-right">{item.route ?? '-'}</dd><dt>时间</dt><dd className="text-right">{formatDateTime(item.timestamp)}</dd></dl><div className="grid gap-2 border-t border-border-default pt-3"><Id label="Event" value={item.eventId} /><Id label="Session" value={item.sessionId} /><Id label="Trace" value={item.traceId} /></div><Button onClick={onOpen}><ExternalLink />打开详情</Button>{item.sessionId ? <Button asChild><Link to="/sessions/$sessionId" params={{ sessionId: item.sessionId }} search={{ eventId: item.eventId }}><GitBranch />查看 Session</Link></Button> : null}</div>; }

function DomainRecord({ mode, open, item, event, loading, error, onClose }: { mode: Mode; open: boolean; item?: Item; event?: MonitorEvent; loading: boolean; error: boolean; onClose: () => void }) { const session = useSessionQuery(event?.sessionId); const related = (session.data ?? []).filter((candidate) => candidate.eventId !== event?.eventId && (candidate.name === 'http.client' || readPath(candidate, ['attributes', 'business.action']) !== undefined || candidate.signalType === 'error')).slice(-8); return <RecordShell open={open} onOpenChange={(value) => !value && onClose()} title={mode === 'business' ? (item as BusinessCatalogItem | undefined)?.action ?? '埋点详情' : (item as ErrorCatalogItem | undefined)?.type ?? '异常详情'} state={loading ? 'loading' : error ? 'error' : event ? 'ready' : 'notFound'} summary={item ? <div className="flex flex-wrap items-center gap-2"><Badge tone={mode === 'business' ? ((item as BusinessCatalogItem).result === 'failed' ? 'danger' : 'good') : 'danger'}>{mode === 'business' ? (item as BusinessCatalogItem).result ?? '未知' : (item as ErrorCatalogItem).kind === 'business_failure' ? '业务失败' : 'Error'}</Badge><span className="text-xs text-text-secondary">{formatDateTime(item.timestamp)} · {item.route ?? '-'}</span></div> : undefined}>{!event ? <div className="grid min-h-40 place-items-center text-sm text-text-secondary">{loading ? '正在加载详情' : error ? '详情加载失败' : '事件不存在'}</div> : <Tabs defaultValue="detail" className="grid h-full grid-rows-[auto_1fr] gap-3"><TabsList className="w-fit"><TabsTrigger value="detail">{mode === 'business' ? 'Properties' : '错误'}</TabsTrigger><TabsTrigger value="related">关联</TabsTrigger><TabsTrigger value="context">上下文</TabsTrigger><TabsTrigger value="raw">Raw</TabsTrigger></TabsList><TabsContent value="detail" className="overflow-auto"><DomainDetail mode={mode} event={event} /></TabsContent><TabsContent value="related" className="overflow-auto"><Related events={related} /></TabsContent><TabsContent value="context" className="overflow-auto"><JsonViewer value={{ resource: event.resource, context: event.context, ids: { eventId: event.eventId, sessionId: event.sessionId, traceId: event.traceId, spanId: event.spanId } }} collapsed={2} /></TabsContent><TabsContent value="raw" className="overflow-auto"><JsonViewer value={event} collapsed={2} /></TabsContent></Tabs>}</RecordShell>; }
function DomainDetail({ mode, event }: { mode: Mode; event: MonitorEvent }) { if (mode === 'business') return <JsonViewer value={readPath(event, ['payload', 'payload.properties']) ?? readPath(event, ['payload', 'properties']) ?? {}} collapsed={2} />; const error = readPath(event, ['payload', 'error']); const stack = readPath(event, ['payload', 'payload.error.stacktrace']) ?? readPath(event, ['payload', 'stack']) ?? (isRecord(error) ? error.stack : undefined); const breadcrumbs = readPath(event, ['payload', 'payload.breadcrumbs']) ?? readPath(event, ['payload', 'breadcrumbs']); const message = readPath(event, ['payload', 'payload.error.message']) ?? (isRecord(error) ? error.message : undefined) ?? readPath(event, ['payload', 'message']) ?? event.name; return <div className="grid gap-4"><Section title="Message" value={message} text /><Section title="Stack" value={stack} text /><Section title="Breadcrumbs" value={breadcrumbs} /></div>; }
function Related({ events }: { events: MonitorEvent[] }) { return events.length ? <div className="grid gap-2">{events.map((event) => <div key={event.eventId} className="rounded-panel border border-border-default p-2 text-xs"><div className="font-medium">{event.name}</div><div className="text-text-secondary">{formatDateTime(event.timestamp)} · {event.status ?? event.signalType}</div></div>)}</div> : <div className="grid min-h-40 place-items-center text-sm text-text-secondary">同 Session 没有相关 HTTP、埋点或错误。</div>; }
function Section({ title, value, text }: { title: string; value: unknown; text?: boolean }) { return <section><h3 className="mb-2 text-sm font-semibold">{title}</h3>{value === undefined ? <p className="text-xs text-text-secondary">没有可用数据。</p> : text ? <pre className="whitespace-pre-wrap break-words rounded-panel border border-border-default bg-subtle p-3 text-xs">{String(value)}</pre> : <JsonViewer value={value} collapsed={2} />}</section>; }

function Pager({ page, pageSize, totalPages, onPatch }: { page: number; pageSize: number; totalPages: number; onPatch: (value: Partial<DomainSearch>) => void }) { return <footer className="flex items-center justify-between border-t border-border-default bg-surface px-3 text-xs"><span>第 {page} / {totalPages} 页</span><div className="flex gap-2"><FilterSelect value={String(pageSize)} placeholder="每页" options={[25,50,100].map((value)=>({value:String(value),label:`${value} 条/页`}))} onChange={(value)=>onPatch({pageSize:Number(value) as 25|50|100,page:undefined,eventId:undefined,detail:undefined})} className="w-28"/><Button size="sm" disabled={page<=1} onClick={()=>onPatch({page:page-1,eventId:undefined,detail:undefined})}>上一页</Button><Button size="sm" disabled={page>=totalPages} onClick={()=>onPatch({page:page+1,eventId:undefined,detail:undefined})}>下一页</Button></div></footer>; }
function EmptyState({ mode, state, onRetry }: { mode: Mode; state: string; onRetry: () => void }) { const text = state === 'loading' ? '正在加载' : state === 'noResults' ? '没有匹配结果' : state === 'empty' ? `暂无${mode === 'business' ? '埋点' : '异常'}数据` : '加载失败'; return <div className="grid h-full place-items-center text-sm text-text-secondary"><div className="text-center">{mode === 'business' ? <MousePointerClick className="mx-auto mb-2 size-5"/> : <AlertTriangle className="mx-auto mb-2 size-5"/>}<p>{text}</p>{state === 'error' ? <Button size="sm" className="mt-2" onClick={onRetry}>重试</Button> : null}</div></div>; }
function CommitInput({ label, value, onCommit }: { label: string; value?: string; onCommit: (value?: string)=>void }) { const [draft,setDraft]=useState(value??''); const debounced=useDebouncedValue(draft,300); useEffect(()=>setDraft(value??''),[value]); useEffect(()=>{const next=debounced.trim()||undefined;if(next!==value)onCommit(next)},[debounced]); return <Input aria-label={label} value={draft} placeholder={`${label} 模糊筛选，自动查询`} onChange={(event)=>{setDraft(event.target.value);if(!event.target.value)onCommit(undefined)}} onKeyDown={(event)=>event.key==='Enter'&&onCommit(draft.trim()||undefined)} className="h-8 min-w-56 flex-1 text-xs"/>; }
function TriSelect({ label, value, onChange }: { label:string; value?:boolean; onChange:(value?:boolean)=>void }) { return <FilterSelect value={value===undefined?undefined:String(value)} placeholder={label} options={[{value:'true',label:`${label}: 是`},{value:'false',label:`${label}: 否`}]} onChange={(next)=>onChange(next===undefined?undefined:next==='true')} className="w-28"/>; }
function Th({children,className}:{children?:React.ReactNode;className?:string}){return <TableHead className={cn('px-2 font-medium',className)}>{children}</TableHead>}; function Td({children,className}:{children?:React.ReactNode;className?:string}){return <TableCell className={cn('overflow-hidden px-2',className)}>{children}</TableCell>};
function Id({label,value}:{label:string;value?:string}){return <div className="flex items-center justify-between gap-2"><span>{label}</span><CopyableId value={value}/></div>};
function businessQuery(search:DomainSearch,page:number,size:number):BusinessCatalogQuery{return clean({...scopeQuery(search),action:search.action,result:list(search.result),limit:size,offset:(page-1)*size})};
function errorQuery(search:DomainSearch,page:number,size:number):ErrorCatalogQuery{return clean({...scopeQuery(search),errorType:search.errorType,mechanism:list(search.mechanism),fatal:search.fatal,handled:search.handled,businessOnly:search.businessOnly,limit:size,offset:(page-1)*size})};
function scopeQuery(search:DomainSearch):SessionFilters{return clean({appKey:list(search.appKey),environment:list(search.environment),appVersion:list(search.appVersion),devicePlatform:list(search.devicePlatform),from:search.from,to:search.to,userId:search.userId,sessionId:search.sessionId,route:list(search.route)})}; function list(value?:string){return value?.split(',').map((item)=>item.trim()).filter(Boolean)}; function clean<T extends Record<string,unknown>>(value:T):T{return Object.fromEntries(Object.entries(value).filter(([,item])=>item!==undefined&&item!==''&&(!Array.isArray(item)||item.length))) as T}; function hasScope(search:DomainSearch){return Boolean(search.from||search.to||search.userId||search.sessionId||search.appVersion||search.environment||search.route)}; function isRecord(value:unknown):value is Record<string,unknown>{return value!==null&&typeof value==='object'&&!Array.isArray(value)}
